spring.profiles.active=local

# Enlace que recibira el usuario en el correo (URL publica del frontend - produccion)
app.frontend-url=https://tecnosoft.ingusb.com/vocacional
app.reset-password-path=/restablecer-contrasena

# Directorio de imagenes Pacho (se crea automaticamente si no existe)
app.upload-dir=./uploads/pacho
